apiVersion: v1
kind: Secret
metadata:
  name: naqqash-secrets
  namespace: naqqash-tea
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  DATABASE_URL: postgresql://user:pass@db:5432/naqqash
  STRIPE_SECRET_KEY: sk_test
  STRIPE_WEBHOOK_SECRET: whsec_test
  EMAIL_HOST_PASSWORD: password
